### 7. Docker Compose

version: '3'
services:
  frontend:
    build: ./frontend-python
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - postgres
      - kafka

  redis:
    image: redis
    ports:
      - "6379:6379"

  recommendation-service:
    build: ./recommendation-service
    depends_on:
      - redis
      - postgres
      - kafka

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: videos
    ports:
      - "5432:5432"

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "video_watched:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
  data-seed:
    build: ./data-seed
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: videos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    depends_on:
      - postgres

  results-nodejs:
    build: ./results-nodejs
    command: node index.js
    volumes:
      - ./results-nodejs:/app
    ports:
      - "3002:3002"
    depends_on:
      - postgres
